### PR TITLE
Add required packages to setup.py

### PR DESCRIPTION
**Pull request by sjmatta**
This is so projects that do a `pip install` on this project get all the projects required to run it. I haven't tested all scripts yet, only a few, so there may be additional packages needed for some scripts.

### CODE REVIEW

**Comment by nathanathan** [comment]
requirements.txt contains all the packages used. We've used `pip install -r requirements.txt` to install the dependencies in the past.

**Comment by sjmatta** [comment]
I created a `virtualenv` in the other, main project (leaving the name off here since the other repo is private), did `pip install -r requirements.txt` in there, then in this repo in the same virtualenv. The problem I ran into was they had different versions of `pymongo` with different APIs so they were incompatible. Is there another method I should be using?

**Comment by nathanathan** [comment]
We should be using updated pymongo versions on all our projects. I'll look
into that.

**Comment by sjmatta** [comment]
This is probably a low priority, since there aren't any API changes, but this is using `numpy 1.10.0.post2` while `grits-api` is using `numpy 1.10.2`. I'll make one last appeal for `setup.py` since it'll allow different versions in transitive dependencies, but I'll concede I'm a novice at Python package management. :)

**Comment by sjmatta** [comment]
Realizing now I probably don't have a solid handle on this at this time. Closing for now.

**Pull request closed without merging**
